development:
  adapter: postgresql
  encoding: unicode
  database: quoteomatic_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: quoteomatic_test
  pool: 5
  host: localhost
